version: '3.8'

services:
  autifyme:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  streamlit:
    build: .
    command: streamlit run src/api/admin.py --server.port=8501 --server.address=0.0.0.0
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - ./src:/app/src

volumes:
  redis_data: