"""
Google Computer Use - Browser Automation Agent

This module provides infrastructure for building browser control agents using
Gemini 2.5 Computer Use model. The model can "see" screenshots and "act" by
generating UI actions like clicks, typing, scrolling, and navigation.

Architecture:
- Screenshot-based: Model analyzes visual state of browser
- Action-driven: Generates structured function calls for UI interactions
- Loop-based: Screenshot → Action → Execute → Screenshot → ...
- Safety-aware: Built-in safety checks for high-risk actions

Key Capabilities:
- Web navigation and form automation
- Data extraction from dynamic pages
- UI testing and verification
- Browser-based workflow automation
- Strong performance on web and Android UIs

Model: gemini-2.5-computer-use-preview-10-2025
Benchmarks: 70% accuracy on Online-Mind2Web
"""

import asyncio
import base64
import os
from dataclasses import dataclass
from enum import Enum
from typing import Any, Callable, Literal

try:
    from google import genai
    from google.genai import types
except ImportError:
    raise ImportError(
        "google-genai package required for Computer Use. "
        "Install with: uv pip install google-genai"
    )


class ActionType(str, Enum):
    """Supported UI action types."""

    OPEN_WEB_BROWSER = "open_web_browser"
    CLICK_AT = "click_at"
    TYPE_TEXT_AT = "type_text_at"
    SCROLL_DOCUMENT = "scroll_document"
    SCROLL_AT = "scroll_at"
    NAVIGATE = "navigate"
    HOVER_AT = "hover_at"
    GO_BACK = "go_back"
    GO_FORWARD = "go_forward"
    SEARCH = "search"
    KEY_COMBINATION = "key_combination"
    DRAG_AND_DROP = "drag_and_drop"
    WAIT_5_SECONDS = "wait_5_seconds"


@dataclass
class ComputerAction:
    """Represents a UI action generated by the model."""

    action_type: str
    args: dict[str, Any]
    requires_confirmation: bool = False
    reasoning: str = ""


@dataclass
class BrowserState:
    """Represents current browser state."""

    screenshot: bytes  # PNG image bytes
    url: str
    title: str
    viewport_width: int = 1440
    viewport_height: int = 900


class ActionExecutor:
    """
    Abstract base class for executing browser actions.

    Implementations should integrate with browser automation tools
    (Playwright, Selenium, Puppeteer, etc.).
    """

    def __init__(self, viewport_width: int = 1440, viewport_height: int = 900):
        """
        Initialize action executor.

        Args:
            viewport_width: Browser viewport width (recommended: 1440)
            viewport_height: Browser viewport height (recommended: 900)
        """
        self.viewport_width = viewport_width
        self.viewport_height = viewport_height

    def normalize_coordinates(self, x: int, y: int) -> tuple[int, int]:
        """
        Convert normalized coordinates (0-999) to actual pixel coordinates.

        Args:
            x: Normalized x coordinate (0-999)
            y: Normalized y coordinate (0-999)

        Returns:
            Tuple of (actual_x, actual_y) in pixels
        """
        actual_x = int((x / 1000) * self.viewport_width)
        actual_y = int((y / 1000) * self.viewport_height)
        return actual_x, actual_y

    async def execute_action(self, action: ComputerAction) -> bool:
        """
        Execute a UI action.

        Args:
            action: ComputerAction to execute

        Returns:
            True if action executed successfully, False otherwise

        Raises:
            NotImplementedError: Must be implemented by subclass
        """
        raise NotImplementedError(
            "ActionExecutor is abstract. Use PlaywrightExecutor or implement custom executor."
        )

    async def get_screenshot(self) -> bytes:
        """
        Capture current browser screenshot.

        Returns:
            Screenshot as PNG bytes

        Raises:
            NotImplementedError: Must be implemented by subclass
        """
        raise NotImplementedError(
            "ActionExecutor is abstract. Use PlaywrightExecutor or implement custom executor."
        )

    async def get_state(self) -> BrowserState:
        """
        Get current browser state.

        Returns:
            BrowserState with screenshot, URL, title

        Raises:
            NotImplementedError: Must be implemented by subclass
        """
        raise NotImplementedError(
            "ActionExecutor is abstract. Use PlaywrightExecutor or implement custom executor."
        )


class ComputerUseAgent:
    """
    Agent for browser automation using Gemini 2.5 Computer Use model.

    Usage:
        # Requires ActionExecutor implementation (Playwright, Selenium, etc.)
        executor = PlaywrightExecutor()  # Your implementation

        agent = ComputerUseAgent(
            action_executor=executor,
            api_key=os.getenv("GOOGLE_API_KEY")
        )

        result = await agent.execute_task(
            goal="Fill out the contact form with test data and submit",
            max_steps=20
        )
    """

    def __init__(
        self,
        action_executor: ActionExecutor,
        api_key: str | None = None,
        system_instruction: str | None = None,
        auto_confirm: bool = False,
        confirmation_callback: Callable[[ComputerAction], bool] | None = None,
    ):
        """
        Initialize Computer Use agent.

        Args:
            action_executor: ActionExecutor instance for browser automation
            api_key: Google API key. If None, reads from GOOGLE_API_KEY env var
            system_instruction: Optional system instructions for agent behavior
            auto_confirm: Auto-approve actions requiring confirmation (use with caution)
            confirmation_callback: Function to handle confirmation requests
                                  (called when action requires user approval)
        """
        self.executor = action_executor
        self.api_key = api_key or os.getenv("GOOGLE_API_KEY")
        self.system_instruction = system_instruction
        self.auto_confirm = auto_confirm
        self.confirmation_callback = confirmation_callback

        if not self.api_key:
            raise ValueError(
                "GOOGLE_API_KEY environment variable or api_key parameter required"
            )

        # Create Gemini client with API key
        self.client = genai.Client(api_key=self.api_key)

        # Model name
        self.model = "gemini-2.5-computer-use-preview-10-2025"

        # Action history
        self.action_history: list[ComputerAction] = []

    def _build_config(
        self, excluded_actions: list[str] | None = None
    ) -> types.GenerateContentConfig:
        """
        Build model configuration with Computer Use tool.

        Args:
            excluded_actions: Optional list of action names to exclude

        Returns:
            GenerateContentConfig with computer_use tool
        """
        tool = types.Tool(
            computer_use=types.ComputerUse(
                environment=types.Environment.ENVIRONMENT_BROWSER,
                excluded_predefined_functions=excluded_actions or [],
            )
        )

        config = types.GenerateContentConfig(tools=[tool])

        if self.system_instruction:
            config.system_instruction = self.system_instruction

        return config

    async def execute_task(
        self,
        goal: str,
        max_steps: int = 20,
        excluded_actions: list[str] | None = None,
        initial_url: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute a browser automation task.

        Args:
            goal: Natural language description of task to accomplish
            max_steps: Maximum number of actions to take
            excluded_actions: Optional list of action names to exclude
            initial_url: Optional starting URL (if not already navigated)

        Returns:
            Dict with:
                - success: bool
                - steps_taken: int
                - final_state: BrowserState
                - actions: list[ComputerAction]
                - error: str (if failed)

        Example:
            result = await agent.execute_task(
                goal="Search for 'Python tutorials' on Google and click the first result",
                max_steps=10,
                initial_url="https://google.com"
            )

            if result["success"]:
                print(f"Task completed in {result['steps_taken']} steps")
        """
        # Navigate to initial URL if provided
        if initial_url:
            nav_action = ComputerAction(
                action_type=ActionType.NAVIGATE,
                args={"url": initial_url},
                reasoning="Navigate to starting URL",
            )
            await self.executor.execute_action(nav_action)

        # Build config
        config = self._build_config(excluded_actions=excluded_actions)

        # Agent loop
        steps_taken = 0
        self.action_history.clear()

        while steps_taken < max_steps:
            try:
                # Get current browser state
                state = await self.executor.get_state()

                # Build prompt
                screenshot_b64 = base64.b64encode(state.screenshot).decode()

                # Create content with screenshot and goal
                contents = [
                    types.Content(
                        role="user",
                        parts=[
                            types.Part.from_text(
                                f"Goal: {goal}\n\n"
                                f"Current URL: {state.url}\n"
                                f"Page title: {state.title}\n"
                                f"Steps taken: {steps_taken}/{max_steps}\n\n"
                                "Analyze the screenshot and take the next action to achieve the goal."
                            ),
                            types.Part.from_uri(
                                mime_type="image/png",
                                uri=f"data:image/png;base64,{screenshot_b64}",
                            ),
                        ],
                    )
                ]

                # Call model
                response = self.client.models.generate_content(
                    model=self.model, contents=contents, config=config
                )

                # Parse response
                if not response.candidates:
                    return {
                        "success": False,
                        "steps_taken": steps_taken,
                        "final_state": state,
                        "actions": self.action_history,
                        "error": "No response candidates from model",
                    }

                candidate = response.candidates[0]

                # Check for function calls (actions)
                if not candidate.content.parts:
                    # Model thinks task is complete
                    return {
                        "success": True,
                        "steps_taken": steps_taken,
                        "final_state": state,
                        "actions": self.action_history,
                    }

                # Extract reasoning text
                reasoning = ""
                for part in candidate.content.parts:
                    if part.text:
                        reasoning = part.text
                        break

                # Extract and execute actions
                actions_executed = False
                for part in candidate.content.parts:
                    if part.function_call:
                        fc = part.function_call
                        action = ComputerAction(
                            action_type=fc.name,
                            args=dict(fc.args),
                            reasoning=reasoning,
                        )

                        # Check safety decision
                        if hasattr(fc, "safety_decision"):
                            if fc.safety_decision.get("decision") == "require_confirmation":
                                action.requires_confirmation = True

                        # Handle confirmation
                        if action.requires_confirmation:
                            if self.auto_confirm:
                                confirmed = True
                            elif self.confirmation_callback:
                                confirmed = self.confirmation_callback(action)
                            else:
                                # Default: skip action
                                confirmed = False

                            if not confirmed:
                                continue  # Skip this action

                        # Execute action
                        success = await self.executor.execute_action(action)
                        if success:
                            self.action_history.append(action)
                            actions_executed = True
                            steps_taken += 1

                if not actions_executed:
                    # No actions executed, task may be complete
                    return {
                        "success": True,
                        "steps_taken": steps_taken,
                        "final_state": state,
                        "actions": self.action_history,
                    }

            except Exception as e:
                state = await self.executor.get_state()
                return {
                    "success": False,
                    "steps_taken": steps_taken,
                    "final_state": state,
                    "actions": self.action_history,
                    "error": str(e),
                }

        # Max steps reached
        state = await self.executor.get_state()
        return {
            "success": False,
            "steps_taken": steps_taken,
            "final_state": state,
            "actions": self.action_history,
            "error": f"Max steps ({max_steps}) reached",
        }


def get_computer_use_agent(
    action_executor: ActionExecutor,
    api_key: str | None = None,
    system_instruction: str | None = None,
    auto_confirm: bool = False,
) -> ComputerUseAgent:
    """
    Factory function to create Computer Use agent.

    Args:
        action_executor: ActionExecutor instance for browser automation
        api_key: Google API key. If None, reads from GOOGLE_API_KEY env var
        system_instruction: System instructions for agent behavior
        auto_confirm: Auto-approve confirmation requests (use with caution)

    Returns:
        Configured ComputerUseAgent instance

    Example:
        # Requires ActionExecutor implementation
        from my_browser_automation import PlaywrightExecutor

        executor = PlaywrightExecutor(viewport_width=1440, viewport_height=900)
        agent = get_computer_use_agent(
            action_executor=executor,
            system_instruction="You are a careful browser automation agent. "
                              "Always verify forms before submitting."
        )

        result = await agent.execute_task(
            goal="Book a flight from NYC to LAX for next Monday",
            max_steps=30
        )
    """
    return ComputerUseAgent(
        action_executor=action_executor,
        api_key=api_key,
        system_instruction=system_instruction,
        auto_confirm=auto_confirm,
    )
