"""
Playwright Implementation for Google Computer Use

This module provides a reference implementation of ActionExecutor using Playwright
for browser automation with Gemini 2.5 Computer Use model.

Installation:
    cd extensions/google_computer_use
    uv pip install -e ".[playwright]"
    playwright install chromium

Usage:
    from google_computer_use import get_computer_use_agent
    from google_computer_use.playwright_executor import PlaywrightExecutor

    async def main():
        executor = PlaywrightExecutor()
        await executor.initialize()

        agent = get_computer_use_agent(action_executor=executor)
        result = await agent.execute_task(
            goal="Search for 'OpenAI' and click the first result",
            initial_url="https://google.com"
        )

        await executor.cleanup()
        print(result)
"""

import asyncio
from typing import Any

try:
    from playwright.async_api import async_playwright, Browser, Page, Playwright
except ImportError:
    raise ImportError(
        "Playwright required for PlaywrightExecutor. "
        "Install with: uv pip install playwright && playwright install chromium"
    )

from .agent import ActionExecutor, ActionType, BrowserState, ComputerAction


class PlaywrightExecutor(ActionExecutor):
    """
    Playwright-based ActionExecutor for Gemini Computer Use.

    Executes UI actions generated by the Computer Use model using Playwright
    browser automation framework.
    """

    def __init__(
        self,
        viewport_width: int = 1440,
        viewport_height: int = 900,
        headless: bool = False,
    ):
        """
        Initialize Playwright executor.

        Args:
            viewport_width: Browser viewport width
            viewport_height: Browser viewport height
            headless: Run browser in headless mode
        """
        super().__init__(viewport_width=viewport_width, viewport_height=viewport_height)
        self.headless = headless

        # Playwright instances
        self._playwright: Playwright | None = None
        self._browser: Browser | None = None
        self._page: Page | None = None

    async def initialize(self) -> None:
        """Initialize Playwright browser instance."""
        self._playwright = await async_playwright().start()
        self._browser = await self._playwright.chromium.launch(headless=self.headless)

        # Create page with specified viewport
        self._page = await self._browser.new_page(
            viewport={
                "width": self.viewport_width,
                "height": self.viewport_height,
            }
        )

    async def cleanup(self) -> None:
        """Cleanup Playwright resources."""
        if self._page:
            await self._page.close()
        if self._browser:
            await self._browser.close()
        if self._playwright:
            await self._playwright.stop()

    async def execute_action(self, action: ComputerAction) -> bool:
        """
        Execute a UI action using Playwright.

        Args:
            action: ComputerAction to execute

        Returns:
            True if action executed successfully, False otherwise
        """
        if not self._page:
            raise RuntimeError("Executor not initialized. Call initialize() first.")

        try:
            action_type = action.action_type
            args = action.args

            if action_type == ActionType.OPEN_WEB_BROWSER:
                # Browser already open, nothing to do
                return True

            elif action_type == ActionType.CLICK_AT:
                x, y = self.normalize_coordinates(args["x"], args["y"])
                await self._page.mouse.click(x, y)
                return True

            elif action_type == ActionType.TYPE_TEXT_AT:
                x, y = self.normalize_coordinates(args["x"], args["y"])
                text = args["text"]

                # Click to focus
                await self._page.mouse.click(x, y)

                # Clear if requested
                if args.get("clear_existing", False):
                    await self._page.keyboard.press("Control+A")
                    await self._page.keyboard.press("Backspace")

                # Type text
                await self._page.keyboard.type(text)

                # Press Enter if requested
                if args.get("press_enter", False):
                    await self._page.keyboard.press("Enter")

                return True

            elif action_type == ActionType.SCROLL_DOCUMENT:
                direction = args["direction"]  # "up", "down", "left", "right"
                magnitude = args.get("magnitude", 1)

                # Calculate scroll amount
                scroll_amount = 100 * magnitude

                if direction == "up":
                    await self._page.mouse.wheel(0, -scroll_amount)
                elif direction == "down":
                    await self._page.mouse.wheel(0, scroll_amount)
                elif direction == "left":
                    await self._page.mouse.wheel(-scroll_amount, 0)
                elif direction == "right":
                    await self._page.mouse.wheel(scroll_amount, 0)

                return True

            elif action_type == ActionType.SCROLL_AT:
                x, y = self.normalize_coordinates(args["x"], args["y"])
                direction = args["direction"]
                magnitude = args.get("magnitude", 1)

                # Move mouse to position
                await self._page.mouse.move(x, y)

                # Scroll
                scroll_amount = 100 * magnitude
                if direction in ["up", "down"]:
                    delta_y = -scroll_amount if direction == "up" else scroll_amount
                    await self._page.mouse.wheel(0, delta_y)
                else:
                    delta_x = -scroll_amount if direction == "left" else scroll_amount
                    await self._page.mouse.wheel(delta_x, 0)

                return True

            elif action_type == ActionType.NAVIGATE:
                url = args["url"]
                await self._page.goto(url, wait_until="networkidle")
                return True

            elif action_type == ActionType.HOVER_AT:
                x, y = self.normalize_coordinates(args["x"], args["y"])
                await self._page.mouse.move(x, y)
                return True

            elif action_type == ActionType.GO_BACK:
                await self._page.go_back(wait_until="networkidle")
                return True

            elif action_type == ActionType.GO_FORWARD:
                await self._page.go_forward(wait_until="networkidle")
                return True

            elif action_type == ActionType.SEARCH:
                # Navigate to Google
                await self._page.goto("https://www.google.com", wait_until="networkidle")
                return True

            elif action_type == ActionType.KEY_COMBINATION:
                keys = args["keys"]  # e.g., "Control+C", "Alt+Tab"
                await self._page.keyboard.press(keys)
                return True

            elif action_type == ActionType.DRAG_AND_DROP:
                from_x, from_y = self.normalize_coordinates(
                    args["from_x"], args["from_y"]
                )
                to_x, to_y = self.normalize_coordinates(args["to_x"], args["to_y"])

                # Perform drag and drop
                await self._page.mouse.move(from_x, from_y)
                await self._page.mouse.down()
                await self._page.mouse.move(to_x, to_y)
                await self._page.mouse.up()

                return True

            elif action_type == ActionType.WAIT_5_SECONDS:
                await asyncio.sleep(5)
                return True

            else:
                print(f"Unknown action type: {action_type}")
                return False

        except Exception as e:
            print(f"Error executing action {action_type}: {e}")
            return False

    async def get_screenshot(self) -> bytes:
        """
        Capture current browser screenshot.

        Returns:
            Screenshot as PNG bytes
        """
        if not self._page:
            raise RuntimeError("Executor not initialized. Call initialize() first.")

        screenshot_bytes = await self._page.screenshot(type="png", full_page=False)
        return screenshot_bytes

    async def get_state(self) -> BrowserState:
        """
        Get current browser state.

        Returns:
            BrowserState with screenshot, URL, title
        """
        if not self._page:
            raise RuntimeError("Executor not initialized. Call initialize() first.")

        screenshot = await self.get_screenshot()
        url = self._page.url
        title = await self._page.title()

        return BrowserState(
            screenshot=screenshot,
            url=url,
            title=title,
            viewport_width=self.viewport_width,
            viewport_height=self.viewport_height,
        )

    async def __aenter__(self):
        """Context manager entry."""
        await self.initialize()
        return self

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        """Context manager exit."""
        await self.cleanup()
